server:
  port: 8888
  tomcat:
    threads:
      max: 1000 # 생성할 수 있는 thread의 총 개수
      min-spare: 250 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 8192 # 수립가능한 connection의 총 개수
    accept-count: 250 # 작업큐의 사이즈
    connection-timeout: 20000 # timeout 판단 기준 시간, 20초

spring:
  application:
    name: dranswer
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:27.96.134.98}:${DB_PORT:5444}/${DB_NAME:svc_plf}?currentSchema=${DB_SCHEMA:swint}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASS:postgres}
  jpa:
    properties:
      hibernate:
        default_catalog: svc_plf
        default_schema: swint
        hbm2ddl:
          auto: none

mybatis:
  type-aliases-package: com.t3q.dranswer.dto

env:
  authUrl: ${AUTH_HOST:http://auth.dev.dranswer-g.co.kr}

  userRealm: ${USER_REALM:service-user-dev}
  userClient: ${USER_CLIENT:login}
  userSecret: ${USER_SECRET:JG6eaVSJVzbUp5Sgp7MAyByrraZX7xNC}
  userAuthUrl: ${env.authUrl}/auth/realms/${env.userRealm}/protocol/openid-connect/auth
  userTokenUrl: ${env.authUrl}/auth/realms/${env.userRealm}/protocol/openid-connect/token
  userSpecUrl: ${env.authUrl}/auth/realms/${env.userRealm}/protocol/openid-connect/token/introspect

  systemRealm: ${SYSTEM_REALM:service-system-dev}
  systemClient: ${SYSTEM_CLIENT:swint}
  systemSecret: ${SYSTEM_SECRET:K91G3XhKY3z2qussprBEAC24cksv0qNk}
  systemAuthUrl: ${env.authUrl}/auth/realms/${env.systemRealm}/protocol/openid-connect/auth
  systemTokenUrl: ${env.authUrl}/auth/realms/${env.systemRealm}/protocol/openid-connect/token
  systemSpecUrl: ${env.authUrl}/auth/realms/${env.systemRealm}/protocol/openid-connect/token/introspect

  cmanUrl: ${CMAN_HOST:http://115.85.182.6:30330}
  callbackUrl: ${LOCAL_HOST:http://localhost:8888/callback}

  accessTokenName: dr_access_token
  refreshTokenName: dr_refresh_token